import { THEMES } from "@/lib/constants";
import type { PublicMenuSnapshot } from "@/types/domain";

export const DEMO_SNAPSHOT: PublicMenuSnapshot = {
  schema_version: 1,
  organization_id: "00000000-0000-0000-0000-000000000001",
  location: {
    id: "00000000-0000-0000-0000-000000000011",
    slug: "demo",
    name: "Osteria del Portico",
    tagline: {
      it: "Cucina bolognese, senza fretta.",
      en: "Bolognese cooking, at its own pace.",
      fr: "Cuisine bolognaise, sans se presser.",
      de: "Bolognesische Küche, ganz in Ruhe.",
      es: "Cocina boloñesa, sin prisas.",
    },
    description: {
      it: "Una piccola osteria contemporanea dove la sfoglia incontra ingredienti di stagione e vini del territorio.",
      en: "A small contemporary osteria where handmade pasta meets seasonal ingredients and local wines.",
      fr: "Une petite osteria contemporaine où les pâtes maison rencontrent les produits de saison.",
      de: "Eine kleine moderne Osteria mit hausgemachter Pasta und saisonalen Zutaten.",
      es: "Una pequeña osteria contemporánea con pasta casera e ingredientes de temporada.",
    },
    address: "Via del Portico 12",
    city: "Bologna",
    phone: "+39 051 000 0000",
    email: "ciao@example.com",
    whatsapp_url: "https://wa.me/390510000000",
    reservation_url: "https://example.com/prenota",
    map_url: "https://maps.google.com/?q=Bologna",
    instagram_url: "https://instagram.com",
    opening_hours: [
      { days: "Lun–Ven", hours: "12:00–14:30 · 19:00–22:30" },
      { days: "Sab–Dom", hours: "12:00–23:00" },
    ],
  },
  menu: {
    id: "00000000-0000-0000-0000-000000000021",
    name: "Menu principale",
    currency: "EUR",
    source_locale: "it",
    active_locales: ["it", "en", "fr", "de", "es"],
    categories: [
      {
        id: "cat-antipasti",
        slug: "per-cominciare",
        name: { it: "Per cominciare", en: "To begin", fr: "Pour commencer", de: "Zum Anfang", es: "Para empezar" },
        description: { it: "Piccoli piatti da condividere.", en: "Small plates made for sharing." },
        items: [
          {
            id: "item-crescentine",
            name: { it: "Crescentine e giardiniera", en: "Crescentine with pickled vegetables", fr: "Crescentine et légumes marinés", de: "Crescentine mit eingelegtem Gemüse", es: "Crescentine con verduras encurtidas" },
            description: { it: "Impasto fritto, giardiniera della casa e squacquerone.", en: "Fried dough, house pickles and squacquerone cheese." },
            ingredients: { it: "Farina, latte, strutto, verdure, squacquerone" },
            price: 12,
            available: true,
            vegetarian: true,
            vegan: false,
            gluten_free: false,
            allergens: ["Glutine", "Latte"],
            variants: [],
          },
          {
            id: "item-uovo",
            name: { it: "Uovo, patata e tartufo", en: "Egg, potato and truffle", fr: "Œuf, pomme de terre et truffe", de: "Ei, Kartoffel und Trüffel", es: "Huevo, patata y trufa" },
            description: { it: "Uovo morbido, crema di patate e tartufo nero.", en: "Soft egg, potato cream and black truffle." },
            price: 14,
            available: true,
            vegetarian: true,
            vegan: false,
            gluten_free: true,
            allergens: ["Uova", "Latte"],
            variants: [],
          },
        ],
      },
      {
        id: "cat-primi",
        slug: "sfoglia",
        name: { it: "La sfoglia", en: "Handmade pasta", fr: "Pâtes maison", de: "Hausgemachte Pasta", es: "Pasta fresca" },
        items: [
          {
            id: "item-tagliatelle",
            name: { it: "Tagliatelle al ragù", en: "Tagliatelle with traditional ragù", fr: "Tagliatelles au ragù", de: "Tagliatelle mit Ragù", es: "Tagliatelle con ragú" },
            description: { it: "Sfoglia tirata a mano e ragù cotto lentamente.", en: "Hand-rolled pasta with slow-cooked ragù." },
            price: 16,
            available: true,
            vegetarian: false,
            vegan: false,
            gluten_free: false,
            allergens: ["Glutine", "Uova", "Sedano"],
            variants: [],
          },
          {
            id: "item-tortelloni",
            name: { it: "Tortelloni burro e salvia", en: "Tortelloni with butter and sage", fr: "Tortelloni au beurre et à la sauge", de: "Tortelloni mit Butter und Salbei", es: "Tortelloni con mantequilla y salvia" },
            description: { it: "Ripieno di ricotta, Parmigiano Reggiano e noce moscata.", en: "Filled with ricotta, Parmigiano Reggiano and nutmeg." },
            price: 17,
            available: true,
            vegetarian: true,
            vegan: false,
            gluten_free: false,
            allergens: ["Glutine", "Uova", "Latte"],
            variants: [],
          },
        ],
      },
      {
        id: "cat-dolci",
        slug: "dolci",
        name: { it: "Dolci", en: "Desserts", fr: "Desserts", de: "Desserts", es: "Postres" },
        items: [
          {
            id: "item-zuppa-inglese",
            name: { it: "Zuppa inglese", en: "Zuppa inglese", fr: "Zuppa inglese", de: "Zuppa inglese", es: "Zuppa inglese" },
            description: { it: "Pan di Spagna, crema e Alchermes.", en: "Sponge cake, custard and Alchermes." },
            price: 8,
            available: true,
            vegetarian: true,
            vegan: false,
            gluten_free: false,
            allergens: ["Glutine", "Uova", "Latte"],
            variants: [],
          },
        ],
      },
    ],
  },
  theme: THEMES.editorial,
  published_at: "2026-07-15T10:00:00.000Z",
  version: 1,
};
